//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * <p>Java class for bookJobRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bookJobRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.haulmont.com/sherlock/adler}jobRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="securePaymentParameters" type="{http://www.haulmont.com/sherlock/adler}securePaymentParameters" minOccurs="0"/&gt;
 *         &lt;element name="requestId" type="{http://www.haulmont.com/sherlock/adler}uuid"/&gt;
 *         &lt;element name="senderJobInfo" type="{http://www.haulmont.com/sherlock/adler}jobInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookJobRequest", propOrder = {
    "securePaymentParameters",
    "requestId",
    "senderJobInfo"
})
@XmlRootElement(name = "BookJobRequest")
public class BookJobRequest
    extends JobRequest
{

    protected SecurePaymentParameters securePaymentParameters;
    @XmlElement(required = true)
    protected String requestId;
    @XmlElement(required = true)
    protected JobInfo senderJobInfo;

    /**
     * Gets the value of the securePaymentParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SecurePaymentParameters }
     *     
     */
    public SecurePaymentParameters getSecurePaymentParameters() {
        return securePaymentParameters;
    }

    /**
     * Sets the value of the securePaymentParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurePaymentParameters }
     *     
     */
    public void setSecurePaymentParameters(SecurePaymentParameters value) {
        this.securePaymentParameters = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the senderJobInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JobInfo }
     *     
     */
    public JobInfo getSenderJobInfo() {
        return senderJobInfo;
    }

    /**
     * Sets the value of the senderJobInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobInfo }
     *     
     */
    public void setSenderJobInfo(JobInfo value) {
        this.senderJobInfo = value;
    }

}
