//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customerDataResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customerDataResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.haulmont.com/sherlock/adler}response"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="referenceEntities" type="{http://www.haulmont.com/sherlock/adler}referenceEntity" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="services" type="{http://www.haulmont.com/sherlock/adler}service" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="pickupAddresses" type="{http://www.haulmont.com/sherlock/adler}customerAddress" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="dropAddresses" type="{http://www.haulmont.com/sherlock/adler}customerAddress" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="contacts" type="{http://www.haulmont.com/sherlock/adler}individualWithStatus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="passengers" type="{http://www.haulmont.com/sherlock/adler}individualWithStatus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="airports" type="{http://www.haulmont.com/sherlock/adler}airport" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="trainStations" type="{http://www.haulmont.com/sherlock/adler}trainStation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="creditCards" type="{http://www.haulmont.com/sherlock/adler}creditCardInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customerDataResponse", propOrder = {
    "referenceEntities",
    "services",
    "pickupAddresses",
    "dropAddresses",
    "contacts",
    "passengers",
    "airports",
    "trainStations",
    "creditCards"
})
public class CustomerDataResponse
    extends Response
{

    protected List<ReferenceEntity> referenceEntities;
    protected List<Service> services;
    protected List<CustomerAddress> pickupAddresses;
    protected List<CustomerAddress> dropAddresses;
    protected List<IndividualWithStatus> contacts;
    protected List<IndividualWithStatus> passengers;
    protected List<Airport> airports;
    protected List<TrainStation> trainStations;
    protected List<CreditCardInfo> creditCards;

    /**
     * Gets the value of the referenceEntities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenceEntities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenceEntities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceEntity }
     * 
     * 
     */
    public List<ReferenceEntity> getReferenceEntities() {
        if (referenceEntities == null) {
            referenceEntities = new ArrayList<ReferenceEntity>();
        }
        return this.referenceEntities;
    }

    /**
     * Gets the value of the services property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the services property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getServices() {
        if (services == null) {
            services = new ArrayList<Service>();
        }
        return this.services;
    }

    /**
     * Gets the value of the pickupAddresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pickupAddresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPickupAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerAddress }
     * 
     * 
     */
    public List<CustomerAddress> getPickupAddresses() {
        if (pickupAddresses == null) {
            pickupAddresses = new ArrayList<CustomerAddress>();
        }
        return this.pickupAddresses;
    }

    /**
     * Gets the value of the dropAddresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dropAddresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDropAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerAddress }
     * 
     * 
     */
    public List<CustomerAddress> getDropAddresses() {
        if (dropAddresses == null) {
            dropAddresses = new ArrayList<CustomerAddress>();
        }
        return this.dropAddresses;
    }

    /**
     * Gets the value of the contacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndividualWithStatus }
     * 
     * 
     */
    public List<IndividualWithStatus> getContacts() {
        if (contacts == null) {
            contacts = new ArrayList<IndividualWithStatus>();
        }
        return this.contacts;
    }

    /**
     * Gets the value of the passengers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passengers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassengers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndividualWithStatus }
     * 
     * 
     */
    public List<IndividualWithStatus> getPassengers() {
        if (passengers == null) {
            passengers = new ArrayList<IndividualWithStatus>();
        }
        return this.passengers;
    }

    /**
     * Gets the value of the airports property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the airports property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAirports().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Airport }
     * 
     * 
     */
    public List<Airport> getAirports() {
        if (airports == null) {
            airports = new ArrayList<Airport>();
        }
        return this.airports;
    }

    /**
     * Gets the value of the trainStations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainStations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainStations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainStation }
     * 
     * 
     */
    public List<TrainStation> getTrainStations() {
        if (trainStations == null) {
            trainStations = new ArrayList<TrainStation>();
        }
        return this.trainStations;
    }

    /**
     * Gets the value of the creditCards property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditCards property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditCards().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditCardInfo }
     * 
     * 
     */
    public List<CreditCardInfo> getCreditCards() {
        if (creditCards == null) {
            creditCards = new ArrayList<CreditCardInfo>();
        }
        return this.creditCards;
    }

}
