//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customerDataRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customerDataRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.haulmont.com/sherlock/adler}request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="caller" type="{http://www.haulmont.com/sherlock/adler}individual" minOccurs="0"/&gt;
 *         &lt;element name="pickupAddress" type="{http://www.haulmont.com/sherlock/adler}coordinatesAddress" minOccurs="0"/&gt;
 *         &lt;element name="dataToLoad" type="{http://www.haulmont.com/sherlock/adler}dataToLoad" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customerDataRequest", propOrder = {
    "accountNumber",
    "pin",
    "caller",
    "pickupAddress",
    "dataToLoad"
})
public class CustomerDataRequest
    extends Request
{

    protected String accountNumber;
    protected String pin;
    protected Individual caller;
    protected CoordinatesAddress pickupAddress;
    protected DataToLoad dataToLoad;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the pin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPin() {
        return pin;
    }

    /**
     * Sets the value of the pin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPin(String value) {
        this.pin = value;
    }

    /**
     * Gets the value of the caller property.
     * 
     * @return
     *     possible object is
     *     {@link Individual }
     *     
     */
    public Individual getCaller() {
        return caller;
    }

    /**
     * Sets the value of the caller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Individual }
     *     
     */
    public void setCaller(Individual value) {
        this.caller = value;
    }

    /**
     * Gets the value of the pickupAddress property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinatesAddress }
     *     
     */
    public CoordinatesAddress getPickupAddress() {
        return pickupAddress;
    }

    /**
     * Sets the value of the pickupAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinatesAddress }
     *     
     */
    public void setPickupAddress(CoordinatesAddress value) {
        this.pickupAddress = value;
    }

    /**
     * Gets the value of the dataToLoad property.
     * 
     * @return
     *     possible object is
     *     {@link DataToLoad }
     *     
     */
    public DataToLoad getDataToLoad() {
        return dataToLoad;
    }

    /**
     * Sets the value of the dataToLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataToLoad }
     *     
     */
    public void setDataToLoad(DataToLoad value) {
        this.dataToLoad = value;
    }

}
