//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cvcRequiredSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cvcRequiredSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="forNewCreditCard" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="forExistingCreditCard" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cvcRequiredSettings", propOrder = {
    "forNewCreditCard",
    "forExistingCreditCard"
})
public class CvcRequiredSettings {

    protected boolean forNewCreditCard;
    protected boolean forExistingCreditCard;

    /**
     * Gets the value of the forNewCreditCard property.
     * 
     */
    public boolean isForNewCreditCard() {
        return forNewCreditCard;
    }

    /**
     * Sets the value of the forNewCreditCard property.
     * 
     */
    public void setForNewCreditCard(boolean value) {
        this.forNewCreditCard = value;
    }

    /**
     * Gets the value of the forExistingCreditCard property.
     * 
     */
    public boolean isForExistingCreditCard() {
        return forExistingCreditCard;
    }

    /**
     * Sets the value of the forExistingCreditCard property.
     * 
     */
    public void setForExistingCreditCard(boolean value) {
        this.forExistingCreditCard = value;
    }

}
