//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataToLoad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataToLoad"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="references" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="services" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="addresses" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="contacts" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="passengers" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="airports" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="trainStations" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="creditCards" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataToLoad", propOrder = {
    "references",
    "services",
    "addresses",
    "contacts",
    "passengers",
    "airports",
    "trainStations",
    "creditCards"
})
public class DataToLoad {

    protected boolean references;
    protected boolean services;
    protected boolean addresses;
    protected boolean contacts;
    protected boolean passengers;
    protected boolean airports;
    protected boolean trainStations;
    protected boolean creditCards;

    /**
     * Gets the value of the references property.
     * 
     */
    public boolean isReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     */
    public void setReferences(boolean value) {
        this.references = value;
    }

    /**
     * Gets the value of the services property.
     * 
     */
    public boolean isServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     */
    public void setServices(boolean value) {
        this.services = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     */
    public boolean isAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     */
    public void setAddresses(boolean value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the contacts property.
     * 
     */
    public boolean isContacts() {
        return contacts;
    }

    /**
     * Sets the value of the contacts property.
     * 
     */
    public void setContacts(boolean value) {
        this.contacts = value;
    }

    /**
     * Gets the value of the passengers property.
     * 
     */
    public boolean isPassengers() {
        return passengers;
    }

    /**
     * Sets the value of the passengers property.
     * 
     */
    public void setPassengers(boolean value) {
        this.passengers = value;
    }

    /**
     * Gets the value of the airports property.
     * 
     */
    public boolean isAirports() {
        return airports;
    }

    /**
     * Sets the value of the airports property.
     * 
     */
    public void setAirports(boolean value) {
        this.airports = value;
    }

    /**
     * Gets the value of the trainStations property.
     * 
     */
    public boolean isTrainStations() {
        return trainStations;
    }

    /**
     * Sets the value of the trainStations property.
     * 
     */
    public void setTrainStations(boolean value) {
        this.trainStations = value;
    }

    /**
     * Gets the value of the creditCards property.
     * 
     */
    public boolean isCreditCards() {
        return creditCards;
    }

    /**
     * Sets the value of the creditCards property.
     * 
     */
    public void setCreditCards(boolean value) {
        this.creditCards = value;
    }

}
