//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import org.springframework.stereotype.Component;

import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dewcis.ptg.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@Component
public class ObjectFactory {

    private final static QName _SchemaValidationFaultDetail_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "SchemaValidationFaultDetail");
    private final static QName _LoginRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "LoginRequest");
    private final static QName _LoginResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "LoginResponse");
    private final static QName _LogoutRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "LogoutRequest");
    private final static QName _LogoutResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "LogoutResponse");
    private final static QName _AccountInfoRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AccountInfoRequest");
    private final static QName _AccountInfoResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AccountInfoResponse");
    private final static QName _PinInfoRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "PinInfoRequest");
    private final static QName _PinInfoResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "PinInfoResponse");
    private final static QName _CallerInfoRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CallerInfoRequest");
    private final static QName _CallerInfoResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CallerInfoResponse");
    private final static QName _CustomerDataRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CustomerDataRequest");
    private final static QName _CustomerDataResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CustomerDataResponse");
    private final static QName _TelephonesEmailsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "TelephonesEmailsRequest");
    private final static QName _TelephonesEmailsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "TelephonesEmailsResponse");
    private final static QName _ReferenceInstancesRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ReferenceInstancesRequest");
    private final static QName _ReferenceInstancesResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ReferenceInstancesResponse");
    private final static QName _RouteSettingsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RouteSettingsRequest");
    private final static QName _RouteSettingsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RouteSettingsResponse");
    private final static QName _AvailableInstructionTypesRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AvailableInstructionTypesRequest");
    private final static QName _AvailableInstructionTypesResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AvailableInstructionTypesResponse");
    private final static QName _AirportsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AirportsRequest");
    private final static QName _AirportsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AirportsResponse");
    private final static QName _TrainStationsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "TrainStationsRequest");
    private final static QName _TrainStationsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "TrainStationsResponse");
    private final static QName _AddressSearchByStringRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AddressSearchByStringRequest");
    private final static QName _AddressSearchByStringResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AddressSearchByStringResponse");
    private final static QName _AddressSearchByCoordinatesRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AddressSearchByCoordinatesRequest");
    private final static QName _AddressSearchByCoordinatesResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AddressSearchByCoordinatesResponse");
    private final static QName _AdlerWsGetDetailedAddressRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AdlerWsGetDetailedAddressRequest");
    private final static QName _AdlerWsGetDetailedAddressResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AdlerWsGetDetailedAddressResponse");
    private final static QName _QuotationRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "QuotationRequest");
    private final static QName _QuotationResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "QuotationResponse");
    private final static QName _DelayRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "DelayRequest");
    private final static QName _DelayResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "DelayResponse");
    private final static QName _ValidateReferencesRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ValidateReferencesRequest");
    private final static QName _ValidateReferencesResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ValidateReferencesResponse");
    private final static QName _ValidateJobRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ValidateJobRequest");
    private final static QName _ValidateJobResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ValidateJobResponse");
    private final static QName _BookJobRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "BookJobRequest");
    private final static QName _BookJobResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "BookJobResponse");
    private final static QName _CompletePaymentRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CompletePaymentRequest");
    private final static QName _CompletePaymentResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CompletePaymentResponse");
    private final static QName _AmendJobRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AmendJobRequest");
    private final static QName _AmendJobResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AmendJobResponse");
    private final static QName _CancelJobRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CancelJobRequest");
    private final static QName _CancelJobResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CancelJobResponse");
    private final static QName _JobStatusRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobStatusRequest");
    private final static QName _JobStatusResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobStatusResponse");
    private final static QName _JobPriceDetailsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobPriceDetailsRequest");
    private final static QName _JobPriceDetailsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobPriceDetailsResponse");
    private final static QName _ReceiptRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ReceiptRequest");
    private final static QName _ReceiptResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ReceiptResponse");
    private final static QName _ZoneInfoRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ZoneInfoRequest");
    private final static QName _ZoneInfoResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ZoneInfoResponse");
    private final static QName _FleetRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "FleetRequest");
    private final static QName _FleetResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "FleetResponse");
    private final static QName _JobStatusChangedRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobStatusChangedRequest");
    private final static QName _JobStatusChangedResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobStatusChangedResponse");
    private final static QName _JobReadyForInvoiceRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobReadyForInvoiceRequest");
    private final static QName _JobReadyForInvoiceResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobReadyForInvoiceResponse");
    private final static QName _RetailRegisterRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailRegisterRequest");
    private final static QName _RetailRegisterResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailRegisterResponse");
    private final static QName _RetailLoginRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLoginRequest");
    private final static QName _RetailLoginResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLoginResponse");
    private final static QName _RetailPasswordRecoveryRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailPasswordRecoveryRequest");
    private final static QName _RetailPasswordRecoveryResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailPasswordRecoveryResponse");
    private final static QName _RetailCheckUserExistsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailCheckUserExistsRequest");
    private final static QName _RetailCheckUserExistsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailCheckUserExistsResponse");
    private final static QName _RetailChangePasswordRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailChangePasswordRequest");
    private final static QName _RetailChangePasswordResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailChangePasswordResponse");
    private final static QName _RetailChangePhoneRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailChangePhoneRequest");
    private final static QName _RetailChangePhoneResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailChangePhoneResponse");
    private final static QName _RetailUpdateProfileRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailUpdateProfileRequest");
    private final static QName _RetailUpdateProfileResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailUpdateProfileResponse");
    private final static QName _RetailLoadProfileRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLoadProfileRequest");
    private final static QName _RetailLoadProfileResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLoadProfileResponse");
    private final static QName _RetailLogoutRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLogoutRequest");
    private final static QName _RetailLogoutResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLogoutResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dewcis.ptg.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchemaValidationFaultDetail }
     * 
     */
    public SchemaValidationFaultDetail createSchemaValidationFaultDetail() {
        return new SchemaValidationFaultDetail();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link AccountInfoRequest }
     * 
     */
    public AccountInfoRequest createAccountInfoRequest() {
        return new AccountInfoRequest();
    }

    /**
     * Create an instance of {@link AccountInfoResponse }
     * 
     */
    public AccountInfoResponse createAccountInfoResponse() {
        return new AccountInfoResponse();
    }

    /**
     * Create an instance of {@link PinRequest }
     * 
     */
    public PinRequest createPinRequest() {
        return new PinRequest();
    }

    /**
     * Create an instance of {@link PinResponse }
     * 
     */
    public PinResponse createPinResponse() {
        return new PinResponse();
    }

    /**
     * Create an instance of {@link CallerInfoRequest }
     * 
     */
    public CallerInfoRequest createCallerInfoRequest() {
        return new CallerInfoRequest();
    }

    /**
     * Create an instance of {@link CallerInfoResponse }
     * 
     */
    public CallerInfoResponse createCallerInfoResponse() {
        return new CallerInfoResponse();
    }

    /**
     * Create an instance of {@link CustomerDataRequest }
     * 
     */
    public CustomerDataRequest createCustomerDataRequest() {
        return new CustomerDataRequest();
    }

    /**
     * Create an instance of {@link CustomerDataResponse }
     * 
     */
    public CustomerDataResponse createCustomerDataResponse() {
        return new CustomerDataResponse();
    }

    /**
     * Create an instance of {@link TelephoneEmailsRequest }
     * 
     */
    public TelephoneEmailsRequest createTelephoneEmailsRequest() {
        return new TelephoneEmailsRequest();
    }

    /**
     * Create an instance of {@link TelephoneEmailsResponse }
     * 
     */
    public TelephoneEmailsResponse createTelephoneEmailsResponse() {
        return new TelephoneEmailsResponse();
    }

    /**
     * Create an instance of {@link ReferenceInstancesRequest }
     * 
     */
    public ReferenceInstancesRequest createReferenceInstancesRequest() {
        return new ReferenceInstancesRequest();
    }

    /**
     * Create an instance of {@link ReferenceInstancesResponse }
     * 
     */
    public ReferenceInstancesResponse createReferenceInstancesResponse() {
        return new ReferenceInstancesResponse();
    }

    /**
     * Create an instance of {@link RouteSettingsRequest }
     * 
     */
    public RouteSettingsRequest createRouteSettingsRequest() {
        return new RouteSettingsRequest();
    }

    /**
     * Create an instance of {@link RouteSettingsResponse }
     * 
     */
    public RouteSettingsResponse createRouteSettingsResponse() {
        return new RouteSettingsResponse();
    }

    /**
     * Create an instance of {@link InstructionTypesRequest }
     * 
     */
    public InstructionTypesRequest createInstructionTypesRequest() {
        return new InstructionTypesRequest();
    }

    /**
     * Create an instance of {@link InstructionTypesResponse }
     * 
     */
    public InstructionTypesResponse createInstructionTypesResponse() {
        return new InstructionTypesResponse();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link AirportsResponse }
     * 
     */
    public AirportsResponse createAirportsResponse() {
        return new AirportsResponse();
    }

    /**
     * Create an instance of {@link TrainStationsResponse }
     * 
     */
    public TrainStationsResponse createTrainStationsResponse() {
        return new TrainStationsResponse();
    }

    /**
     * Create an instance of {@link AddressSearchByStringRequest }
     * 
     */
    public AddressSearchByStringRequest createAddressSearchByStringRequest() {
        return new AddressSearchByStringRequest();
    }

    /**
     * Create an instance of {@link AddressSearchResponse }
     * 
     */
    public AddressSearchResponse createAddressSearchResponse() {
        return new AddressSearchResponse();
    }

    /**
     * Create an instance of {@link AddressSearchByCoordinatesRequest }
     * 
     */
    public AddressSearchByCoordinatesRequest createAddressSearchByCoordinatesRequest() {
        return new AddressSearchByCoordinatesRequest();
    }

    /**
     * Create an instance of {@link AdlerWsGetDetailedAddressRequest }
     * 
     */
    public AdlerWsGetDetailedAddressRequest createAdlerWsGetDetailedAddressRequest() {
        return new AdlerWsGetDetailedAddressRequest();
    }

    /**
     * Create an instance of {@link JobRequest }
     * 
     */
    public JobRequest createJobRequest() {
        return new JobRequest();
    }

    /**
     * Create an instance of {@link QuotationResponse }
     * 
     */
    public QuotationResponse createQuotationResponse() {
        return new QuotationResponse();
    }

    /**
     * Create an instance of {@link DelayRequest }
     * 
     */
    public DelayRequest createDelayRequest() {
        return new DelayRequest();
    }

    /**
     * Create an instance of {@link DelayResponse }
     * 
     */
    public DelayResponse createDelayResponse() {
        return new DelayResponse();
    }

    /**
     * Create an instance of {@link ValidateReferencesRequest }
     * 
     */
    public ValidateReferencesRequest createValidateReferencesRequest() {
        return new ValidateReferencesRequest();
    }

    /**
     * Create an instance of {@link ValidateReferencesResponse }
     * 
     */
    public ValidateReferencesResponse createValidateReferencesResponse() {
        return new ValidateReferencesResponse();
    }

    /**
     * Create an instance of {@link JobValidationResponse }
     * 
     */
    public JobValidationResponse createJobValidationResponse() {
        return new JobValidationResponse();
    }

    /**
     * Create an instance of {@link BookJobRequest }
     * 
     */
    public BookJobRequest createBookJobRequest() {
        return new BookJobRequest();
    }

    /**
     * Create an instance of {@link BookJobResponse }
     * 
     */
    public BookJobResponse createBookJobResponse() {
        return new BookJobResponse();
    }

    /**
     * Create an instance of {@link CompletePaymentRequest }
     * 
     */
    public CompletePaymentRequest createCompletePaymentRequest() {
        return new CompletePaymentRequest();
    }

    /**
     * Create an instance of {@link AmendJobRequest }
     * 
     */
    public AmendJobRequest createAmendJobRequest() {
        return new AmendJobRequest();
    }

    /**
     * Create an instance of {@link CancelJobRequest }
     * 
     */
    public CancelJobRequest createCancelJobRequest() {
        return new CancelJobRequest();
    }

    /**
     * Create an instance of {@link CancelJobResponse }
     * 
     */
    public CancelJobResponse createCancelJobResponse() {
        return new CancelJobResponse();
    }

    /**
     * Create an instance of {@link JobIdRequest }
     * 
     */
    public JobIdRequest createJobIdRequest() {
        return new JobIdRequest();
    }

    /**
     * Create an instance of {@link JobStatusResponse }
     * 
     */
    public JobStatusResponse createJobStatusResponse() {
        return new JobStatusResponse();
    }

    /**
     * Create an instance of {@link JobPriceDetailsRequest }
     * 
     */
    public JobPriceDetailsRequest createJobPriceDetailsRequest() {
        return new JobPriceDetailsRequest();
    }

    /**
     * Create an instance of {@link JobPriceDetailsResponse }
     * 
     */
    public JobPriceDetailsResponse createJobPriceDetailsResponse() {
        return new JobPriceDetailsResponse();
    }

    /**
     * Create an instance of {@link ReceiptRequest }
     * 
     */
    public ReceiptRequest createReceiptRequest() {
        return new ReceiptRequest();
    }

    /**
     * Create an instance of {@link ReceiptResponse }
     * 
     */
    public ReceiptResponse createReceiptResponse() {
        return new ReceiptResponse();
    }

    /**
     * Create an instance of {@link ZoneInfoRequest }
     * 
     */
    public ZoneInfoRequest createZoneInfoRequest() {
        return new ZoneInfoRequest();
    }

    /**
     * Create an instance of {@link ZoneInfoResponse }
     * 
     */
    public ZoneInfoResponse createZoneInfoResponse() {
        return new ZoneInfoResponse();
    }

    /**
     * Create an instance of {@link FleetRequest }
     * 
     */
    public FleetRequest createFleetRequest() {
        return new FleetRequest();
    }

    /**
     * Create an instance of {@link FleetResponse }
     * 
     */
    public FleetResponse createFleetResponse() {
        return new FleetResponse();
    }

    /**
     * Create an instance of {@link JobStatusChangedRequest }
     * 
     */
    public JobStatusChangedRequest createJobStatusChangedRequest() {
        return new JobStatusChangedRequest();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link JobReadyForInvoiceRequest }
     * 
     */
    public JobReadyForInvoiceRequest createJobReadyForInvoiceRequest() {
        return new JobReadyForInvoiceRequest();
    }

    /**
     * Create an instance of {@link RetailRegisterRequest }
     * 
     */
    public RetailRegisterRequest createRetailRegisterRequest() {
        return new RetailRegisterRequest();
    }

    /**
     * Create an instance of {@link RetailLoginRequest }
     * 
     */
    public RetailLoginRequest createRetailLoginRequest() {
        return new RetailLoginRequest();
    }

    /**
     * Create an instance of {@link RetailLoginResponse }
     * 
     */
    public RetailLoginResponse createRetailLoginResponse() {
        return new RetailLoginResponse();
    }

    /**
     * Create an instance of {@link RetailPasswordRecoveryRequest }
     * 
     */
    public RetailPasswordRecoveryRequest createRetailPasswordRecoveryRequest() {
        return new RetailPasswordRecoveryRequest();
    }

    /**
     * Create an instance of {@link RetailCheckUserExistsRequest }
     * 
     */
    public RetailCheckUserExistsRequest createRetailCheckUserExistsRequest() {
        return new RetailCheckUserExistsRequest();
    }

    /**
     * Create an instance of {@link RetailChangePasswordRequest }
     * 
     */
    public RetailChangePasswordRequest createRetailChangePasswordRequest() {
        return new RetailChangePasswordRequest();
    }

    /**
     * Create an instance of {@link RetailChangePhoneRequest }
     * 
     */
    public RetailChangePhoneRequest createRetailChangePhoneRequest() {
        return new RetailChangePhoneRequest();
    }

    /**
     * Create an instance of {@link RetailUpdateProfileRequest }
     * 
     */
    public RetailUpdateProfileRequest createRetailUpdateProfileRequest() {
        return new RetailUpdateProfileRequest();
    }

    /**
     * Create an instance of {@link RetailLoadProfileResponse }
     * 
     */
    public RetailLoadProfileResponse createRetailLoadProfileResponse() {
        return new RetailLoadProfileResponse();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Pin }
     * 
     */
    public Pin createPin() {
        return new Pin();
    }

    /**
     * Create an instance of {@link Individual }
     * 
     */
    public Individual createIndividual() {
        return new Individual();
    }

    /**
     * Create an instance of {@link IndividualWithStatus }
     * 
     */
    public IndividualWithStatus createIndividualWithStatus() {
        return new IndividualWithStatus();
    }

    /**
     * Create an instance of {@link CustomerBookingSettings }
     * 
     */
    public CustomerBookingSettings createCustomerBookingSettings() {
        return new CustomerBookingSettings();
    }

    /**
     * Create an instance of {@link CvcRequiredSettings }
     * 
     */
    public CvcRequiredSettings createCvcRequiredSettings() {
        return new CvcRequiredSettings();
    }

    /**
     * Create an instance of {@link AirportStopSettings }
     * 
     */
    public AirportStopSettings createAirportStopSettings() {
        return new AirportStopSettings();
    }

    /**
     * Create an instance of {@link TrainStopSettings }
     * 
     */
    public TrainStopSettings createTrainStopSettings() {
        return new TrainStopSettings();
    }

    /**
     * Create an instance of {@link CustomerProfileSettings }
     * 
     */
    public CustomerProfileSettings createCustomerProfileSettings() {
        return new CustomerProfileSettings();
    }

    /**
     * Create an instance of {@link CoordinatesAddress }
     * 
     */
    public CoordinatesAddress createCoordinatesAddress() {
        return new CoordinatesAddress();
    }

    /**
     * Create an instance of {@link DataToLoad }
     * 
     */
    public DataToLoad createDataToLoad() {
        return new DataToLoad();
    }

    /**
     * Create an instance of {@link CustomerAddress }
     * 
     */
    public CustomerAddress createCustomerAddress() {
        return new CustomerAddress();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link CreditCardInfo }
     * 
     */
    public CreditCardInfo createCreditCardInfo() {
        return new CreditCardInfo();
    }

    /**
     * Create an instance of {@link ReferenceEntity }
     * 
     */
    public ReferenceEntity createReferenceEntity() {
        return new ReferenceEntity();
    }

    /**
     * Create an instance of {@link SpecialInstructionType }
     * 
     */
    public SpecialInstructionType createSpecialInstructionType() {
        return new SpecialInstructionType();
    }

    /**
     * Create an instance of {@link SpecialInstructionParameter }
     * 
     */
    public SpecialInstructionParameter createSpecialInstructionParameter() {
        return new SpecialInstructionParameter();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link Terminal }
     * 
     */
    public Terminal createTerminal() {
        return new Terminal();
    }

    /**
     * Create an instance of {@link TrainStation }
     * 
     */
    public TrainStation createTrainStation() {
        return new TrainStation();
    }

    /**
     * Create an instance of {@link TrainStationMeetingPoint }
     * 
     */
    public TrainStationMeetingPoint createTrainStationMeetingPoint() {
        return new TrainStationMeetingPoint();
    }

    /**
     * Create an instance of {@link AddressSearchRequest }
     * 
     */
    public AddressSearchRequest createAddressSearchRequest() {
        return new AddressSearchRequest();
    }

    /**
     * Create an instance of {@link PickupStatistics }
     * 
     */
    public PickupStatistics createPickupStatistics() {
        return new PickupStatistics();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Fare }
     * 
     */
    public Fare createFare() {
        return new Fare();
    }

    /**
     * Create an instance of {@link WaitingTime }
     * 
     */
    public WaitingTime createWaitingTime() {
        return new WaitingTime();
    }

    /**
     * Create an instance of {@link PriceAdjustment }
     * 
     */
    public PriceAdjustment createPriceAdjustment() {
        return new PriceAdjustment();
    }

    /**
     * Create an instance of {@link SpecialInstruction }
     * 
     */
    public SpecialInstruction createSpecialInstruction() {
        return new SpecialInstruction();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link ReferenceValidationInfo }
     * 
     */
    public ReferenceValidationInfo createReferenceValidationInfo() {
        return new ReferenceValidationInfo();
    }

    /**
     * Create an instance of {@link BaseJob }
     * 
     */
    public BaseJob createBaseJob() {
        return new BaseJob();
    }

    /**
     * Create an instance of {@link Caller }
     * 
     */
    public Caller createCaller() {
        return new Caller();
    }

    /**
     * Create an instance of {@link CreditCard }
     * 
     */
    public CreditCard createCreditCard() {
        return new CreditCard();
    }

    /**
     * Create an instance of {@link BillingAddress }
     * 
     */
    public BillingAddress createBillingAddress() {
        return new BillingAddress();
    }

    /**
     * Create an instance of {@link RouteInfo }
     * 
     */
    public RouteInfo createRouteInfo() {
        return new RouteInfo();
    }

    /**
     * Create an instance of {@link JobInfo }
     * 
     */
    public JobInfo createJobInfo() {
        return new JobInfo();
    }

    /**
     * Create an instance of {@link BaseActor }
     * 
     */
    public BaseActor createBaseActor() {
        return new BaseActor();
    }

    /**
     * Create an instance of {@link Actor }
     * 
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link Stop }
     * 
     */
    public Stop createStop() {
        return new Stop();
    }

    /**
     * Create an instance of {@link AirportStopDetails }
     * 
     */
    public AirportStopDetails createAirportStopDetails() {
        return new AirportStopDetails();
    }

    /**
     * Create an instance of {@link TrainStopDetails }
     * 
     */
    public TrainStopDetails createTrainStopDetails() {
        return new TrainStopDetails();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link ValidationMessage }
     * 
     */
    public ValidationMessage createValidationMessage() {
        return new ValidationMessage();
    }

    /**
     * Create an instance of {@link SecurePaymentParameters }
     * 
     */
    public SecurePaymentParameters createSecurePaymentParameters() {
        return new SecurePaymentParameters();
    }

    /**
     * Create an instance of {@link RedirectInfo }
     * 
     */
    public RedirectInfo createRedirectInfo() {
        return new RedirectInfo();
    }

    /**
     * Create an instance of {@link RedirectParameter }
     * 
     */
    public RedirectParameter createRedirectParameter() {
        return new RedirectParameter();
    }

    /**
     * Create an instance of {@link SecurePaymentParameter }
     * 
     */
    public SecurePaymentParameter createSecurePaymentParameter() {
        return new SecurePaymentParameter();
    }

    /**
     * Create an instance of {@link JobDriverInfo }
     * 
     */
    public JobDriverInfo createJobDriverInfo() {
        return new JobDriverInfo();
    }

    /**
     * Create an instance of {@link FinalJob }
     * 
     */
    public FinalJob createFinalJob() {
        return new FinalJob();
    }

    /**
     * Create an instance of {@link FinalStop }
     * 
     */
    public FinalStop createFinalStop() {
        return new FinalStop();
    }

    /**
     * Create an instance of {@link AdditionalPayment }
     * 
     */
    public AdditionalPayment createAdditionalPayment() {
        return new AdditionalPayment();
    }

    /**
     * Create an instance of {@link JobExtra }
     * 
     */
    public JobExtra createJobExtra() {
        return new JobExtra();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link Charge }
     * 
     */
    public Charge createCharge() {
        return new Charge();
    }

    /**
     * Create an instance of {@link DriverInfo }
     * 
     */
    public DriverInfo createDriverInfo() {
        return new DriverInfo();
    }

 
}
