//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.haulmont.com/sherlock/adler", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dewcis.ptg.beans;
