//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="request"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sessionId" type="{http://www.haulmont.com/sherlock/adler}uuid"/&gt;
 *         &lt;element name="retailSessionId" type="{http://www.haulmont.com/sherlock/adler}uuid" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "request", propOrder = {
    "sessionId",
    "retailSessionId"
})
@XmlSeeAlso({
    LogoutRequest.class,
    AccountInfoRequest.class,
    PinRequest.class,
    CallerInfoRequest.class,
    CustomerDataRequest.class,
    TelephoneEmailsRequest.class,
    ReferenceInstancesRequest.class,
    RouteSettingsRequest.class,
    InstructionTypesRequest.class,
    DelayRequest.class,
    ValidateReferencesRequest.class,
    JobRequest.class,
    CompletePaymentRequest.class,
    AmendJobRequest.class,
    JobIdRequest.class,
    ReceiptRequest.class,
    ZoneInfoRequest.class,
    FleetRequest.class,
    JobStatusChangedRequest.class,
    JobReadyForInvoiceRequest.class,
    RetailRegisterRequest.class,
    RetailLoginRequest.class,
    RetailPasswordRecoveryRequest.class,
    RetailCheckUserExistsRequest.class,
    RetailChangePasswordRequest.class,
    RetailChangePhoneRequest.class,
    RetailUpdateProfileRequest.class,
    AddressSearchRequest.class
})
public class Request {

    @XmlElement(required = true)
    protected String sessionId;
    protected String retailSessionId;

    /**
     * Gets the value of the sessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets the value of the sessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionId(String value) {
        this.sessionId = value;
    }

    /**
     * Gets the value of the retailSessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetailSessionId() {
        return retailSessionId;
    }

    /**
     * Sets the value of the retailSessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetailSessionId(String value) {
        this.retailSessionId = value;
    }

}
