//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for routeInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="routeInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="destinationUnknown" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="waitAndReturn" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="asDirected" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="asDirectedHours" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "routeInfo", propOrder = {
    "destinationUnknown",
    "waitAndReturn",
    "asDirected",
    "asDirectedHours"
})
public class RouteInfo {

    protected boolean destinationUnknown;
    protected boolean waitAndReturn;
    protected boolean asDirected;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar asDirectedHours;

    /**
     * Gets the value of the destinationUnknown property.
     * 
     */
    public boolean isDestinationUnknown() {
        return destinationUnknown;
    }

    /**
     * Sets the value of the destinationUnknown property.
     * 
     */
    public void setDestinationUnknown(boolean value) {
        this.destinationUnknown = value;
    }

    /**
     * Gets the value of the waitAndReturn property.
     * 
     */
    public boolean isWaitAndReturn() {
        return waitAndReturn;
    }

    /**
     * Sets the value of the waitAndReturn property.
     * 
     */
    public void setWaitAndReturn(boolean value) {
        this.waitAndReturn = value;
    }

    /**
     * Gets the value of the asDirected property.
     * 
     */
    public boolean isAsDirected() {
        return asDirected;
    }

    /**
     * Sets the value of the asDirected property.
     * 
     */
    public void setAsDirected(boolean value) {
        this.asDirected = value;
    }

    /**
     * Gets the value of the asDirectedHours property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAsDirectedHours() {
        return asDirectedHours;
    }

    /**
     * Sets the value of the asDirectedHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAsDirectedHours(XMLGregorianCalendar value) {
        this.asDirectedHours = value;
    }

}
