//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for routeSettingsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="routeSettingsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.haulmont.com/sherlock/adler}response"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="destinationUnknownAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="waitAndReturnAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="asDirectedAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "routeSettingsResponse", propOrder = {
    "destinationUnknownAvailable",
    "waitAndReturnAvailable",
    "asDirectedAvailable"
})
public class RouteSettingsResponse
    extends Response
{

    protected boolean destinationUnknownAvailable;
    protected boolean waitAndReturnAvailable;
    protected boolean asDirectedAvailable;

    /**
     * Gets the value of the destinationUnknownAvailable property.
     * 
     */
    public boolean isDestinationUnknownAvailable() {
        return destinationUnknownAvailable;
    }

    /**
     * Sets the value of the destinationUnknownAvailable property.
     * 
     */
    public void setDestinationUnknownAvailable(boolean value) {
        this.destinationUnknownAvailable = value;
    }

    /**
     * Gets the value of the waitAndReturnAvailable property.
     * 
     */
    public boolean isWaitAndReturnAvailable() {
        return waitAndReturnAvailable;
    }

    /**
     * Sets the value of the waitAndReturnAvailable property.
     * 
     */
    public void setWaitAndReturnAvailable(boolean value) {
        this.waitAndReturnAvailable = value;
    }

    /**
     * Gets the value of the asDirectedAvailable property.
     * 
     */
    public boolean isAsDirectedAvailable() {
        return asDirectedAvailable;
    }

    /**
     * Sets the value of the asDirectedAvailable property.
     * 
     */
    public void setAsDirectedAvailable(boolean value) {
        this.asDirectedAvailable = value;
    }

}
