//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for securePaymentParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="securePaymentParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="acceptHeader" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userAgent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="termUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "securePaymentParameters", propOrder = {
    "acceptHeader",
    "userAgent",
    "termUrl"
})
public class SecurePaymentParameters {

    @XmlElement(required = true)
    protected String acceptHeader;
    @XmlElement(required = true)
    protected String userAgent;
    @XmlElement(required = true)
    protected String termUrl;

    /**
     * Gets the value of the acceptHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptHeader() {
        return acceptHeader;
    }

    /**
     * Sets the value of the acceptHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptHeader(String value) {
        this.acceptHeader = value;
    }

    /**
     * Gets the value of the userAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Sets the value of the userAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserAgent(String value) {
        this.userAgent = value;
    }

    /**
     * Gets the value of the termUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermUrl() {
        return termUrl;
    }

    /**
     * Sets the value of the termUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermUrl(String value) {
        this.termUrl = value;
    }

}
