//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 06:56:16 AM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stop complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stop"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operationType" type="{http://www.haulmont.com/sherlock/adler}stopOperationType"/&gt;
 *         &lt;element name="address" type="{http://www.haulmont.com/sherlock/adler}address"/&gt;
 *         &lt;element name="contact" type="{http://www.haulmont.com/sherlock/adler}baseActor" minOccurs="0"/&gt;
 *         &lt;element name="airportDetails" type="{http://www.haulmont.com/sherlock/adler}airportStopDetails" minOccurs="0"/&gt;
 *         &lt;element name="trainDetails" type="{http://www.haulmont.com/sherlock/adler}trainStopDetails" minOccurs="0"/&gt;
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stop", propOrder = {
    "operationType",
    "address",
    "contact",
    "airportDetails",
    "trainDetails",
    "notes"
})
@XmlSeeAlso({
    FinalStop.class
})
public class Stop {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StopOperationType operationType;
    @XmlElement(required = true)
    protected Address address;
    protected BaseActor contact;
    protected AirportStopDetails airportDetails;
    protected TrainStopDetails trainDetails;
    protected String notes;

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link StopOperationType }
     *     
     */
    public StopOperationType getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopOperationType }
     *     
     */
    public void setOperationType(StopOperationType value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link BaseActor }
     *     
     */
    public BaseActor getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseActor }
     *     
     */
    public void setContact(BaseActor value) {
        this.contact = value;
    }

    /**
     * Gets the value of the airportDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AirportStopDetails }
     *     
     */
    public AirportStopDetails getAirportDetails() {
        return airportDetails;
    }

    /**
     * Sets the value of the airportDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportStopDetails }
     *     
     */
    public void setAirportDetails(AirportStopDetails value) {
        this.airportDetails = value;
    }

    /**
     * Gets the value of the trainDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TrainStopDetails }
     *     
     */
    public TrainStopDetails getTrainDetails() {
        return trainDetails;
    }

    /**
     * Sets the value of the trainDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainStopDetails }
     *     
     */
    public void setTrainDetails(TrainStopDetails value) {
        this.trainDetails = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
